### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by gitbyte** [followyourheart/sina-weibo-crawler#3]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with sina-weibo-crawler. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable sina-weibo-crawler on @Sourcegraph by going to https://sourcegraph.com/github.com/followyourheart/sina-weibo-crawler and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by followyourheart** [comment]
Done
